/* Unpacked extension in a disposable profile; provider traffic and optional grant dialogs use deterministic fixtures. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
(async () => {
    const root = path.resolve(__dirname, '..');
    const profile = await fs.mkdtemp(path.join(os.tmpdir(), 'duzelt-ui-'));
    const artifacts = path.join(root, 'output/playwright');
    const assets = path.join(root, 'design/claude-assets');
    await fs.mkdir(artifacts, { recursive: true });
    await fs.mkdir(assets, { recursive: true });
    const checks = [];
    let offscreenSkipLinkCaptures = 0;
    let context;
    try {
        context = await chromium.launchPersistentContext(profile, { channel: 'chromium', headless: true, args: [`--disable-extensions-except=${root}`, `--load-extension=${root}`], viewport: { width: 1024, height: 900 } });
        const worker = context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
        const extensionId = new URL(worker.url()).host;
        await worker.evaluate(() => {
            globalThis.testCalls = [];
            globalThis.fixtureFailure = false;
            globalThis.fixtureLocalOffline = false;
            globalThis.fixtureLocalForbidden = false;
            globalThis.fixtureEmptyModels = false;
            globalThis.fixtureHoldLocal = false;
            globalThis.releaseLocalRequest = null;
            chrome.permissions.contains = (value, callback) => callback(true);
            globalThis.fetch = async (url, init) => {
                const body = init.body && String(init.body).startsWith('{') ? JSON.parse(init.body) : null;
                testCalls.push({ url: String(url), method: init.method, model: body?.model || body?.model_id || body?.config?.modules?.prompt_templating?.model?.name, userText: body?.messages?.find(item => item.role === 'user')?.content });
                if (fixtureFailure) return new Response(JSON.stringify({ error: { message: 'never expose fixture detail', code: 'invalid_api_key' } }), { status: 401 });
                if (String(url).includes('/identity/token') || String(url).endsWith('/oauth/token')) return new Response(JSON.stringify({ access_token: 'fixture-access-token', token_type: 'Bearer', expires_in: 3600 }), { status: 200 });
                if (String(url).endsWith('/api/tags') && fixtureLocalOffline) throw new TypeError('fixture local network failure');
                if (String(url).endsWith('/api/tags') && fixtureLocalForbidden) return new Response('Forbidden', { status: 403 });
                if (String(url).endsWith('/api/tags') && fixtureHoldLocal) await new Promise(resolve => { releaseLocalRequest = resolve; });
                if (String(url).endsWith('/api/tags') && fixtureEmptyModels) return new Response(JSON.stringify({ models: [] }), { status: 200 });
                if (String(url).endsWith('/api/tags')) return new Response(JSON.stringify({ models: [{ name: 'qwen2.5:7b', capabilities: ['completion', 'tools'] }, { name: 'fixture-chat:latest', capabilities: ['chat'] }, { name: 'nomic-embed-text:latest', capabilities: ['embedding'] }] }), { status: 200 });
                if (!body) return new Response(JSON.stringify({ data: [{ id: 'test-model', name: 'Test Model' }] }), { status: 200 });
                const output = JSON.stringify({ corrected_text: 'Bu bir test metnidir.' });
                return new Response(JSON.stringify(String(url).endsWith('/v2/completion') ? { final_result: { choices: [{ finish_reason: 'stop', message: { content: output } }] } } : String(url).includes(':generateContent') ? { candidates: [{ finishReason: 'STOP', content: { parts: [{ text: output }] } }] } : { choices: [{ finish_reason: 'stop', message: { content: output } }] }), { status: 200 });
            };
        });
        const errors = [];
        const options = await context.newPage();
        options.on('pageerror', error => errors.push(error.message));
        await options.emulateMedia({ reducedMotion: 'reduce' });
        await options.addInitScript(() => {
            globalThis.permissionRequests = [];
            globalThis.copiedCommands = [];
            globalThis.clipboardFailure = false;
            Object.defineProperty(navigator, 'clipboard', { value: { writeText: async value => {
                if (clipboardFailure) throw new Error('fixture clipboard denied');
                copiedCommands.push(value);
            } }, configurable: true });
            globalThis.grantPermission = true;
            globalThis.holdPermission = false;
            globalThis.releasePermission = null;
            globalThis.holdPromptSet = false;
            globalThis.releasePromptSet = null;
            globalThis.containsPermission = sessionStorage.getItem('fixture-permission') !== 'denied';
            chrome.permissions.contains = (request, callback) => callback(containsPermission);
            chrome.permissions.request = (request, callback) => {
                permissionRequests.push(request);
                if (holdPermission) releasePermission = () => callback(grantPermission);
                else callback(grantPermission);
            };
            const nativeSet = chrome.storage.local.set.bind(chrome.storage.local);
            chrome.storage.local.set = (values, callback) => {
                if (holdPromptSet && Object.hasOwn(values, 'custom_system_prompt')) {
                    return nativeSet(values, () => { releasePromptSet = () => callback(); });
                }
                return nativeSet(values, callback);
            };
        });
        const load = async () => {
            await options.goto(`chrome-extension://${extensionId}/options/options.html`);
            await options.waitForFunction(() => document.getElementById('system-prompt').value.length > 0 && !document.getElementById('test-btn').disabled);
        };
        const statusHas = async text => { try { await options.waitForFunction(value => document.getElementById('connection-status').textContent.includes(value), text); } catch (error) { console.error({expectedStatus:text,actualStatus:await options.locator('#connection-status').innerText()}); throw error; } };
        const chooseProvider = async id => {
            if (await options.locator('#provider-select').getAttribute('aria-expanded') !== 'true') await options.locator('#provider-select').click();
            await options.locator('#provider-search').fill(id);
            await options.locator('#provider-options [data-value=' + JSON.stringify(id) + ']').click();
        };
        const waitIdle = async () => options.waitForFunction(() => !document.getElementById('provider-select').disabled);
        const save = async () => { await options.locator('#save-api-btn').click(); await waitIdle(); await statusHas('kaydedildi'); };
        const prepareCapture = async menu => {
            await options.evaluate(() => {
                document.activeElement?.blur();
                window.scrollTo(0, 0);
            });
            await options.evaluate(() => new Promise(resolve => setTimeout(resolve, 0)));
            if (menu) await options.evaluate(kind => {
                // Reopen the already-tested menu without putting keyboard focus in the reference image.
                if (kind === 'provider') providerPicker.open({ focus: false });
                else modelPicker.open({ all: true, focus: false });
            }, menu);
            await options.waitForFunction(() => scrollY === 0 && !document.querySelector('.skip-link:focus'));
        };
        const referenceCapture = async (capture, menu) => {
            await prepareCapture(menu);
            const skipLink = options.locator('.skip-link');
            const originalStyle = await skipLink.getAttribute('style');
            const unfocusedAndOffscreen = await skipLink.evaluate(node => !node.matches(':focus') && node.getBoundingClientRect().bottom < 0);
            assert.equal(unfocusedAndOffscreen, true, 'Only an unfocused skip-link above the viewport may be suppressed for capture');
            // Chromium's beyond-viewport clip can include an offscreen fixed link after scrolling.
            // Suppress that capture artifact only while taking the image; restore the UI immediately.
            await skipLink.evaluate(node => { node.style.visibility = 'hidden'; });
            offscreenSkipLinkCaptures += 1;
            try { await capture(); }
            finally {
                await skipLink.evaluate((node, style) => {
                    if (style === null) node.removeAttribute('style');
                    else node.setAttribute('style', style);
                }, originalStyle);
            }
        };
        const capturePage = async (file, menu) => referenceCapture(() => options.screenshot({ path: file, fullPage: true }), menu);
        const captureSetup = async file => referenceCapture(() => options.locator('#local-setup').screenshot({ path: file }));
        const saveStateIs = async (id, state) => {
            await options.waitForFunction(({ id, state }) => document.getElementById(id)?.dataset.state === state, { id, state });
            if (id === 'connection-save-state') {
                assert.ok((await options.locator('#connection-save-title').innerText()).trim());
                assert.ok((await options.locator('#connection-save-detail').innerText()).trim());
            }
        };
        const assertCommandLayout = async (scheme, width) => {
            const layout = await options.locator('#local-setup .command-row').evaluateAll(rows => rows.filter(row => row.getClientRects().length).map(row => {
                const code = row.querySelector(':scope > code');
                const button = row.querySelector(':scope > .copy-command');
                if (!code || !button) return { valid: false };
                const codeBounds = code.getBoundingClientRect();
                const buttonBounds = button.getBoundingClientRect();
                return { valid: true, code: { x: codeBounds.x, y: codeBounds.y, width: codeBounds.width, height: codeBounds.height, right: codeBounds.right, bottom: codeBounds.bottom }, button: { x: buttonBounds.x, y: buttonBounds.y, width: buttonBounds.width, height: buttonBounds.height, right: buttonBounds.right } };
            }));
            assert.ok(layout.length >= 2, `${scheme} ${width}px visible command rows`);
            for (const row of layout) {
                assert.equal(row.valid, true, `${scheme} ${width}px direct code/copy pair`);
                if (width > 520) {
                    assert.ok(Math.abs(row.code.y - row.button.y) <= 1, `${scheme} ${width}px code/copy top alignment`);
                    assert.ok(Math.abs(row.code.height - row.button.height) <= 1, `${scheme} ${width}px code/copy height alignment`);
                    assert.ok(Math.abs(row.button.width - 116) <= 1, `${scheme} ${width}px fixed copy width`);
                    assert.ok(row.code.right <= row.button.x + 1, `${scheme} ${width}px command columns do not overlap`);
                } else {
                    assert.ok(row.button.y >= row.code.bottom - 1, `${scheme} ${width}px copy below command`);
                    assert.ok(Math.abs(row.code.x - row.button.x) <= 1, `${scheme} ${width}px stacked left edges align`);
                    assert.ok(Math.abs(row.code.right - row.button.right) <= 1, `${scheme} ${width}px stacked right edges align`);
                    assert.ok(row.button.height >= 40, `${scheme} ${width}px copy touch target`);
                }
                assert.ok(row.code.width > 40, `${scheme} ${width}px readable command column`);
                assert.ok(Math.abs(row.button.right - layout[0].button.right) <= 1, `${scheme} ${width}px copy right edges align`);
            }
            assert.equal(await options.locator('#local-setup summary').evaluateAll(nodes => nodes.filter(node => node.getClientRects().length).every(node => {
                const bounds = node.getBoundingClientRect();
                return bounds.left >= 0 && bounds.right <= innerWidth + 1 && node.scrollWidth <= node.clientWidth + 1;
            })), true, `${scheme} ${width}px details summaries fit`);
            assert.equal(await options.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `${scheme} guide ${width}px overflow`);
        };
        await load();
        await saveStateIs('connection-save-state', 'incomplete');
        assert.match(await options.locator('#connection-save-detail').innerText(), /henüz kaydedilmedi/i);
        assert.match(await options.locator('#usage-note').innerText(), /kayıtlı bağlantısı yok/i);
        await saveStateIs('prompt-save-state', 'saved');
        assert.equal(await options.locator('#openai-key').getAttribute('type'), 'password');
        await options.locator('#provider-select').click();
        assert.ok(await options.locator('#provider-options [role=option]').count() > 200);
        assert.equal(await options.locator('#provider-search').isVisible(), true);
        await options.locator('#provider-search').fill('openrouter');
        assert.equal(await options.locator('#provider-options [role=option]').count(), 1);
        await options.locator('#connection').screenshot({ path: path.join(artifacts, 'provider-search.png') });
        await options.keyboard.press('Escape');
        assert.equal(await options.locator('#provider-panel').isVisible(), false);
        assert.equal(await options.locator('#provider-current-name').innerText(), 'OpenAI');
        await options.locator('#provider-select').click();
        await options.locator('#provider-search').fill('openrouter');
        await options.locator('h1').click();
        assert.equal(await options.locator('#provider-panel').isVisible(), false);
        assert.equal(await options.locator('#provider-current-name').innerText(), 'OpenAI');
        checks.push('Sağlayıcı araması açılan seçim listesinin içinde; filtreleme, Escape ve dışarı tıklama etkin bağlantıyı değiştirmiyor.');
        await options.locator('#provider-select').focus();
        await options.keyboard.press('ArrowDown');
        await options.locator('#provider-search').fill('openrouter');
        await options.keyboard.press('ArrowDown');
        await options.keyboard.press('Enter');
        assert.equal(await options.locator('#provider-current-name').innerText(), 'OpenRouter');
        assert.equal(await options.locator('#provider-panel').isVisible(), false);
        assert.equal(await options.locator('#active-provider').innerText(), 'OpenAI');
        await options.locator('#provider-select').focus();
        await options.keyboard.press('End');
        await options.keyboard.press('Enter');
        assert.equal(await options.locator('#provider-current-name').innerText(), 'Özel sağlayıcı');
        await options.locator('#provider-select').focus();
        await options.keyboard.press('Home');
        const activeChoice = await options.locator('#provider-search').getAttribute('aria-activedescendant');
        assert.equal(await options.locator('#' + activeChoice).getAttribute('data-value'), await options.locator('#provider-options [role=option]').first().getAttribute('data-value'));
        await options.keyboard.press('Escape');
        await options.locator('[data-provider="openai"]').click();
        checks.push('Sağlayıcı listesi klavyeyle açılıp aranıp seçiliyor; Home/End ve Escape çalışıyor, yalnız Kaydet etkin bağlantıyı değiştiriyor.');
        await options.locator('#test-btn').click();
        await statusHas('API anahtarı');
        assert.equal(await worker.evaluate(() => testCalls.length), 0);
        checks.push('Eksik anahtar, ağ isteği yapılmadan gösteriliyor; katalog yerel olarak yükleniyor.');
        await options.locator('#openai-key').fill('Türkçe geçersiz anahtar');
        await options.locator('#save-api-btn').click();
        await statusHas('geçersiz');
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config), undefined);
        checks.push('Geçersiz anahtar depoya yazılmıyor.');
        await worker.evaluate(() => chrome.storage.local.set({ openai_api_key: 'fixture-openai-legacy' }));
        await load();
        assert.equal(await options.locator('#openai-key').inputValue(), 'fixture-openai-legacy');
        assert.equal(await options.locator('#provider-model').inputValue(), 'gpt-4o');
        await save();
        await saveStateIs('connection-save-state', 'saved');
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.providers.openai.apiKey), 'fixture-openai-legacy');
        checks.push('Eski OpenAI anahtarı ve gpt-4o, merkezi yapılandırmaya kayıpsız taşınıyor.');
        await options.locator('[data-provider="openrouter"]').click();
        await options.locator('#provider-model').fill('openai/gpt-4o-mini');
        await options.locator('#openai-key').fill('fixture-openrouter');
        await saveStateIs('connection-save-state', 'draft');
        await options.evaluate(() => { grantPermission = false; });
        await options.locator('#save-api-btn').click();
        await statusHas('izni verilmedi');
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.activeProviderId), 'openai');
        assert.deepEqual(await options.evaluate(() => permissionRequests.at(-1).origins), ['https://openrouter.ai/*']);
        await options.evaluate(() => { grantPermission = true; });
        await save();
        await saveStateIs('connection-save-state', 'saved');
        const config = await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config);
        assert.equal(config.activeProviderId, 'openrouter');
        assert.equal(config.providers.openai.apiKey, 'fixture-openai-legacy');
        checks.push('OpenRouter için belirli alan izni; izin reddi aktif seçimi koruyor, izin sonrası ayrı profiller kaydediliyor.');
        await options.locator('#provider-model').fill('unsaved-model');
        await options.locator('#openai-key').fill('unsaved-secret');
        await saveStateIs('connection-save-state', 'draft');
        await options.locator('#test-btn').click();
        await statusHas('Bağlantı başarılı');
        const call = await worker.evaluate(() => testCalls.at(-1));
        assert.equal(call.model, 'openai/gpt-4o-mini');
        assert.equal(call.url, 'https://openrouter.ai/api/v1/chat/completions');
        assert.equal(call.userText, 'Bu bir test metnidir.');
        await saveStateIs('connection-save-state', 'draft');
        checks.push('Test yalnız kaydedilmiş sağlayıcı/modeli ve kısa örnek metni kullanıyor.');
        await options.locator('[data-provider="openai"]').click();
        await saveStateIs('connection-save-state', 'inactive');
        assert.equal(await options.locator('#provider-model').inputValue(), 'gpt-4o');
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.activeProviderId), 'openrouter');
        await options.locator('[data-provider="openrouter"]').click();
        await saveStateIs('connection-save-state', 'draft');
        assert.equal(await options.locator('#provider-model').inputValue(), 'unsaved-model');
        checks.push('Kayıt durumu eksik, taslak, kaydedilmiş ve kayıtlı ama etkin olmayan profili ayırıyor; taslaklar sağlayıcı değişiminde korunuyor ve test kaydetmiyor.');
        await options.locator('#refresh-models').click();
        await statusHas('sağlayıcıdan alındı');
        assert.equal(await worker.evaluate(() => testCalls.at(-1).url), 'https://openrouter.ai/api/v1/models');
        await options.locator('#provider-model').fill('test');
        assert.equal(await options.locator('#model-options [role=option]').first().getAttribute('data-value'), 'test-model');
        checks.push('Model yenileme kullanıcı tıklamasıyla kayıtlı bağlantıdan alınıyor.');
        await worker.evaluate(() => { fixtureFailure = true; });
        await options.locator('#test-btn').click();
        await statusHas('kabul etmedi');
        assert.equal((await options.locator('#connection-status').innerText()).includes('never expose'), false);
        await worker.evaluate(() => { fixtureFailure = false; });
        checks.push('Bağlantı hatası güvenli metinle gösteriliyor; sağlayıcının ham mesajı açığa çıkmıyor.');
        await chooseProvider('github-copilot');
        assert.equal(await options.locator('#save-api-btn').isDisabled(), true);
        assert.match(await options.locator('#provider-note').innerText(), /CLI|runtime|kimlik/);
        checks.push('Özel ürün girişi ve çalışma ortamı isteyen kayıtlar açıklamalarıyla görünür; yanlış API anahtarı yoluyla etkinleştirilemiyor.');
        await chooseProvider('azure');
        assert.equal(await options.locator('#profile-resourceName').count(), 1);
        await options.locator('[data-provider="llamacpp"]').click();
        await waitIdle();
        assert.equal(await options.locator('#base-url').inputValue(), 'http://127.0.0.1:8080/v1');
        const callsBeforeLocal = await worker.evaluate(() => testCalls.length);
        await options.evaluate(() => { grantPermission = false; });
        await options.locator('[data-provider="ollama"]').click();
        await waitIdle();
        await statusHas('izni verilmedi');
        assert.equal(await worker.evaluate(() => testCalls.length), callsBeforeLocal);
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.activeProviderId), 'openrouter');
        await options.evaluate(() => { grantPermission = true; });
        await options.locator('[data-provider="ollama"]').click();
        await waitIdle();
        assert.equal(await options.locator('[data-provider="ollama"]').getAttribute('aria-pressed'), 'true');
        assert.equal(await options.locator('#base-url').isVisible(), true);
        assert.equal(await options.locator('#base-url').inputValue(), 'http://127.0.0.1:11434/v1');
        assert.equal(await options.locator('#provider-key-group').isVisible(), false);
        assert.equal(await options.locator('#openai-key').isDisabled(), true);
        assert.equal(await worker.evaluate(() => testCalls.at(-1).url), 'http://127.0.0.1:11434/api/tags');
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.providers.ollama), undefined);
        if (await options.locator('#model-toggle').getAttribute('aria-expanded') !== 'true') await options.locator('#model-toggle').click();
        assert.equal(await options.locator('#model-options [role=option]').count(), 2);
        assert.equal(await options.locator('#model-options [role=option]').first().getAttribute('data-value'), 'qwen2.5:7b');
        await options.locator('#connection').screenshot({ path: path.join(artifacts, 'ollama-model-list.png') });
        await options.locator('#provider-model').press('Escape');
        assert.equal(await options.locator('#model-panel').isVisible(), false);
        checks.push('Ollama seçilince izin sonrası modeller otomatik listeleniyor; izin reddinde istek yok ve keşif etkin sağlayıcıyı değiştirmiyor.');
        await options.locator('#model-toggle').click();
        await options.locator('#model-options [data-value="fixture-chat:latest"]').click();
        assert.equal(await options.locator('#provider-model').inputValue(), 'fixture-chat:latest');
        await saveStateIs('connection-save-state', 'draft');
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.providers.ollama), undefined);
        await options.locator('#provider-model').fill('manual-local-id');
        await options.locator('#refresh-models').click();
        await waitIdle();
        assert.equal(await options.locator('#provider-model').inputValue(), 'manual-local-id');
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.activeProviderId), 'openrouter');
        checks.push('Birden çok yerel model listeden seçilebiliyor; elle yazılan ad yenilemede korunuyor, model seçimi ve keşif kaydetmeden etkinleşmiyor.');
        await options.locator('#base-url').fill('http://localhost:11434/v1');
        await options.locator('#provider-model').fill('');
        await options.locator('#refresh-models').click();
        await waitIdle();
        assert.equal(await worker.evaluate(() => testCalls.at(-1).url), 'http://localhost:11434/api/tags');
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.providers.ollama), undefined);
        checks.push('Yerel adresi kaydetmeden yeni adresten modeller alınabiliyor; diğer kayıtlar ve etkin bağlantı korunuyor.');
        await save();
        assert.equal(await options.locator('#connection-state').innerText(), 'Ayar gerekli');
        await saveStateIs('connection-save-state', 'incomplete');
        assert.deepEqual(await options.evaluate(() => permissionRequests.at(-1).origins), ['http://localhost:11434/*']);
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.providers.ollama.baseURL), 'http://localhost:11434/v1');
        checks.push('Ollama ve llama.cpp kartları görünür; yerel adres doğrudan düzenlenip anahtarsız localhost profili olarak kaydediliyor.');
        await options.locator('#refresh-models').click();
        await statusHas('yerel model bulundu');
        assert.equal(await worker.evaluate(() => testCalls.at(-1).url), 'http://localhost:11434/api/tags');
        await options.locator('#provider-model').fill('');
        assert.equal(await options.locator('#model-options [role=option]').count(), 2);
        assert.equal(await options.locator('#model-options [role=option]').first().getAttribute('data-value'), 'qwen2.5:7b');
        assert.match(await options.locator('#model-help').innerText(), /yerel model/);
        if (await options.locator('#model-toggle').getAttribute('aria-expanded') !== 'true') await options.locator('#model-toggle').click();
        await options.locator('#model-options [data-value="qwen2.5:7b"]').click();
        assert.equal(await options.locator('#provider-model').inputValue(), 'qwen2.5:7b');
        await saveStateIs('connection-save-state', 'draft');
        await save();
        await saveStateIs('connection-save-state', 'saved');
        assert.equal(await options.locator('#connection-state').innerText(), 'Ayarlar kayıtlı');
        const afterLocalSave = await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config);
        assert.deepEqual(afterLocalSave.providers.openai, config.providers.openai);
        assert.deepEqual(afterLocalSave.providers.openrouter, config.providers.openrouter);
        await options.locator('#test-btn').click();
        await statusHas('Bağlantı başarılı');
        assert.equal(await worker.evaluate(() => testCalls.at(-1).url), 'http://localhost:11434/v1/chat/completions');
        checks.push('Model bilinmeden yerel adres kaydedilip modeller getiriliyor; embedding modeli ayrılıyor, seçilen metin modeli kaydedilip test ediliyor.');
        await worker.evaluate(() => { fixtureHoldLocal = true; releaseLocalRequest = null; });
        await options.locator('#refresh-models').click();
        await worker.evaluate(() => new Promise((resolve, reject) => {
            let attempts = 0;
            const check = () => typeof releaseLocalRequest === 'function' ? resolve() : ++attempts < 100 ? setTimeout(check, 20) : reject(new Error('Delayed local fixture did not start'));
            check();
        }));
        assert.equal(await options.locator('#provider-select').isDisabled(), true);
        assert.equal(await options.locator('[data-provider="ollama"]').isDisabled(), true);
        assert.equal(await options.locator('#base-url').isDisabled(), false);
        await options.locator('#base-url').fill('http://127.0.0.1:11434/v1');
        await saveStateIs('connection-save-state', 'draft');
        await worker.evaluate(() => { fixtureHoldLocal = false; releaseLocalRequest(); });
        await waitIdle();
        assert.equal(await options.locator('#model-options [role=option]').count(), 0);
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.providers.ollama.baseURL), 'http://localhost:11434/v1');
        await options.locator('#refresh-models').click();
        await waitIdle();
        assert.equal(await worker.evaluate(() => testCalls.at(-1).url), 'http://127.0.0.1:11434/api/tags');
        checks.push('Adres değişince eski model listesi temizleniyor; önceki adrese ait gecikmiş yanıt yeni adresin listesine karışmıyor.');
        await worker.evaluate(() => { fixtureLocalOffline = true; });
        await options.locator('#refresh-models').click();
        await waitIdle();
        await statusHas('Yerel sunucu');
        assert.equal(await options.locator('#local-setup').isVisible(), true);
        if (!await options.locator('#local-setup-details').evaluate(node => node.open)) await options.locator('#local-setup-details > summary').click();
        assert.equal(await options.locator('#ollama-start-command').count(), 0);
        assert.equal(await options.locator('#copy-start-command').count(), 0);
        assert.equal(await options.locator('#local-fetch-models').count(), 0);
        assert.equal(await options.locator('#ollama-origin-command').textContent(), 'OLLAMA_ORIGINS=chrome-extension://' + extensionId + ' ollama serve');
        assert.equal(await options.locator('#ollama-stop-command').textContent(), 'brew services stop ollama');
        await options.locator('#copy-stop-command').click();
        assert.equal(await options.evaluate(() => copiedCommands.at(-1)), 'brew services stop ollama');
        const copyButton = options.locator('#copy-origin-command');
        const beforeCopy = await copyButton.boundingBox();
        await copyButton.click();
        assert.equal(await options.evaluate(() => copiedCommands.at(-1)), 'OLLAMA_ORIGINS=chrome-extension://' + extensionId + ' ollama serve');
        await options.waitForFunction(() => document.querySelector('#copy-origin-command .copy-label').textContent.includes('Kopyalandı'));
        const afterCopy = await copyButton.boundingBox();
        assert.ok(Math.abs(afterCopy.width - beforeCopy.width) <= 1, 'Copy feedback must preserve button width');
        assert.ok(Math.abs(afterCopy.height - beforeCopy.height) <= 1, 'Copy feedback must preserve button height');
        assert.match(await options.locator('#local-copy-status').innerText(), /kopyalandı/i);
        assert.equal(await options.locator('#local-copy-status').getAttribute('role'), 'status');
        assert.equal(await options.locator('#local-copy-status').getAttribute('aria-live'), 'polite');
        await options.locator('#local-setup').screenshot({ path: path.join(artifacts, 'ollama-copy-success.png') });
        const copiedBeforeFailure = await options.evaluate(() => copiedCommands.length);
        await options.evaluate(() => { clipboardFailure = true; });
        await copyButton.click();
        await options.waitForFunction(() => document.getElementById('local-copy-status').textContent.includes('Kopyalanamadı'));
        assert.equal(await options.evaluate(() => copiedCommands.length), copiedBeforeFailure);
        assert.equal(await options.locator('#local-copy-status').isVisible(), true);
        assert.equal(await copyButton.locator('.copy-label').innerText(), 'Yeniden dene');
        const afterFailedCopy = await copyButton.boundingBox();
        assert.ok(Math.abs(afterFailedCopy.width - beforeCopy.width) <= 1, 'Failed copy feedback must preserve width');
        assert.ok(Math.abs(afterFailedCopy.height - beforeCopy.height) <= 1, 'Failed copy feedback must preserve height');
        await options.evaluate(() => { clipboardFailure = false; });
        await copyButton.click();
        await options.waitForFunction(() => document.querySelector('#copy-origin-command .copy-label').textContent === 'Kopyalandı');
        assert.equal(await options.evaluate(() => copiedCommands.length), copiedBeforeFailure + 1);
        await options.waitForFunction(() => document.querySelector('#copy-origin-command .copy-label').textContent === 'Kopyala', null, { timeout: 4000 });
        if (!await options.locator('.model-install-help').evaluate(node => node.open)) await options.locator('.model-install-help > summary').click();
        for (const [buttonId, command] of [['copy-list-command', 'ollama list'], ['copy-pull-command', 'ollama pull <model-adı>']]) {
            await options.locator('#' + buttonId).click();
            assert.equal(await options.evaluate(() => copiedCommands.at(-1)), command);
        }
        assert.match(await options.locator('#local-setup').innerText(), /Ctrl\+C/);
        assert.match(await options.locator('#local-setup').innerText(), /brew services stop ollama/);
        assert.match(await options.locator('#local-setup').innerText(), /Terminal[\s\S]*(?:açık|kapatma)/i);
        checks.push('Tek Ollama komutu eklenti kimliğini içeriyor; kopyalama başarı/hatası canlı metinle bildiriliyor, düğme ölçüsü değişmiyor ve önce durdurma/Terminali açık bırakma adımları görünür.');
        await worker.evaluate(() => { fixtureLocalOffline = false; fixtureLocalForbidden = true; });
        await options.locator('#refresh-models').click();
        await waitIdle();
        await statusHas('Yerel sunucu');
        if (!await options.locator('#local-setup-details').evaluate(node => node.open)) await options.locator('#local-setup-details > summary').click();
        assert.equal(await options.locator('#ollama-origin-command').textContent(), 'OLLAMA_ORIGINS=chrome-extension://' + extensionId + ' ollama serve');
        await options.locator('#copy-origin-command').click();
        assert.equal(await options.evaluate(() => copiedCommands.at(-1)), 'OLLAMA_ORIGINS=chrome-extension://' + extensionId + ' ollama serve');
        checks.push('Kapalı yerel sunucu ve erişim reddi komutlarla açıklanıyor; Kopyala doğru eklenti kimliğiyle komutu verir, komut çalıştırılmaz.');
        await worker.evaluate(() => { fixtureLocalForbidden = false; fixtureEmptyModels = true; });
        await options.locator('#refresh-models').click();
        await waitIdle();
        assert.equal(await options.locator('#model-options [role=option]').count(), 0);
        assert.match(await options.locator('#model-help').innerText(), /model|Model/);
        await worker.evaluate(() => { fixtureEmptyModels = false; });
        checks.push('Boş model listesi anlaşılır durumda gösteriliyor; eski model önerileri kalmıyor.');
        const callsBeforeNoGrant = await worker.evaluate(() => testCalls.length);
        await options.evaluate(() => sessionStorage.setItem('fixture-permission', 'denied'));
        await load();
        await options.waitForFunction(() => document.getElementById('active-provider').textContent.includes('Ollama') && document.getElementById('refresh-models').getAttribute('aria-busy') === 'false');
        assert.equal(await worker.evaluate(() => testCalls.length), callsBeforeNoGrant);
        assert.equal(await options.locator('#model-options [role=option]').count(), 0);
        checks.push('Kayıtlı yerel ayarlar açılırken bağlantı izni yoksa otomatik istek veya izin penceresi açılmıyor.');
        await options.evaluate(() => sessionStorage.removeItem('fixture-permission'));
        await load();
        await options.waitForFunction(() => document.getElementById('model-help').textContent.includes('2 yerel model'));
        await waitIdle();
        assert.equal(await worker.evaluate(() => testCalls.length), callsBeforeNoGrant + 1);
        assert.equal(await worker.evaluate(() => testCalls.at(-1).url), 'http://localhost:11434/api/tags');
        assert.equal(await options.locator('#model-panel').isVisible(), false);
        assert.equal(await options.locator('#provider-model').inputValue(), 'qwen2.5:7b');
        checks.push('Kayıtlı yerel ayarlar açılırken önceden verilen izinle modeller geliyor; seçim ve kayıtlar korunuyor, liste kendiliğinden açılmıyor.');
        await chooseProvider('watsonx');
        await options.locator('#provider-model').fill('fixture-native-chat');
        await options.locator('#openai-key').fill('fixture-ibm-key');
        await options.locator('#profile-projectId').fill('fixture-project');
        await save();
        assert.deepEqual(await options.evaluate(() => permissionRequests.at(-1).origins), ['https://us-south.ml.cloud.ibm.com/*', 'https://iam.cloud.ibm.com/*']);
        await options.locator('#test-btn').click();
        await statusHas('Bağlantı başarılı');
        assert.ok((await worker.evaluate(() => testCalls.at(-1).url)).includes('/ml/v1/text/chat?version='));
        checks.push('IBM IAM ve inference adresleri için ayrı izinler isteniyor; API anahtarıyla belirteç alıp yerel fixture düzeltmesi tamamlanıyor.');
        await chooseProvider('sap-ai-core');
        assert.equal(await options.locator('#provider-key-group').isVisible(), false);
        assert.equal(await options.locator('#profile-clientSecret').getAttribute('type'), 'password');
        await options.locator('#profile-clientId').fill('fixture-client');
        await options.locator('#profile-clientSecret').fill('fixture-sap-secret');
        await options.locator('#profile-tokenURL').fill('https://auth.example/oauth/token');
        await options.locator('#profile-deploymentId').fill('fixture-deployment');
        await options.locator('#profile-resourceGroup').fill('fixture-group');
        await options.locator('#provider-model').fill('gpt-4o');
        await options.locator('#base-url').fill('https://sap.example');
        assert.equal(await options.locator('#profile-sapMode').inputValue(), 'orchestration');
        await save();
        assert.deepEqual(await options.evaluate(() => permissionRequests.at(-1).origins), ['https://sap.example/*', 'https://auth.example/*']);
        await options.locator('#test-btn').click();
        await statusHas('Bağlantı başarılı');
        assert.ok((await worker.evaluate(() => testCalls.at(-1).url)).endsWith('/v2/completion'));
        assert.equal(await worker.evaluate(async () => JSON.stringify(await chrome.storage.local.get(null)).includes('fixture-access-token')), false);
        assert.equal(await worker.evaluate(async () => Object.hasOwn(await chrome.storage.sync.get(null), 'ai_provider_config')), false);
        checks.push('SAP giriş alanları ve orkestrasyon seçimi merkezi formda çalışıyor; iki adres izinli, alınan belirteç ve profiller Sync depoya yazılmıyor.');
        await chooseProvider('custom');
        await options.locator('#provider-model').fill('my-model');
        await options.locator('#advanced-settings').evaluate(node => { node.open = true; });
        await options.locator('#base-url').fill('http://remote.example/v1');
        await options.locator('#save-api-btn').click();
        await statusHas('HTTPS');
        await options.locator('#base-url').fill('https://proxy.example/v1?key=bad');
        await options.locator('#save-api-btn').click();
        await statusHas('sorgu');
        const active = await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.activeProviderId);
        assert.equal(active, 'sap-ai-core');
        checks.push('Güvensiz uzak HTTP ve anahtar içerebilecek sorgulu adresler kaydedilmiyor.');
        await options.locator('#system-prompt').fill('Yalnız imla ve noktalama hatalarını düzelt.');
        await saveStateIs('prompt-save-state', 'draft');
        await options.locator('#save-prompt-btn').click();
        await options.waitForFunction(() => document.getElementById('status').textContent.includes('kaydedildi'));
        await saveStateIs('prompt-save-state', 'saved');
        await load();
        assert.equal(await options.locator('#system-prompt').inputValue(), 'Yalnız imla ve noktalama hatalarını düzelt.');
        await saveStateIs('prompt-save-state', 'saved');
        await options.locator('#reset-prompt-btn').click();
        await saveStateIs('prompt-save-state', 'draft');
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('custom_system_prompt')).custom_system_prompt), 'Yalnız imla ve noktalama hatalarını düzelt.');
        await options.locator('#system-prompt').fill('');
        await saveStateIs('prompt-save-state', 'draft');
        await options.locator('#save-prompt-btn').click();
        await options.waitForFunction(() => document.getElementById('status').textContent.includes('Varsayılan'));
        await saveStateIs('prompt-save-state', 'saved');
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('custom_system_prompt')).custom_system_prompt), undefined);
        checks.push('Ortak özel kurallar local alanda korunuyor; boş kaydetmek varsayılana dönüyor.');
        checks.push('Kural durumu düzenleme ve varsayılana dönüşü taslak olarak gösteriyor; yalnız Kaydet kalıcı değiştiriyor, boş/default kurallar eşdeğer.');
        await options.locator('[data-provider="openai"]').click();
        await options.locator('#openai-key').fill('');
        await save();
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('openai_api_key')).openai_api_key), undefined);
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.providers.openai.apiKey), '');
        checks.push('Anahtar silme eski kaydı da temizliyor; başka sağlayıcıya gizli geçiş yapılmıyor.');
        await options.locator('#provider-model').fill('fixture-model-A');
        await options.locator('#openai-key').fill('fixture-race-key');
        await options.evaluate(() => { holdPermission = true; releasePermission = null; });
        await options.locator('#save-api-btn').click();
        await options.waitForFunction(() => typeof releasePermission === 'function');
        await options.locator('#provider-model').fill('fixture-model-B');
        await options.evaluate(() => { holdPermission = false; releasePermission(); });
        await waitIdle();
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.providers.openai.model), 'fixture-model-A');
        assert.equal(await options.locator('#provider-model').inputValue(), 'fixture-model-B');
        await saveStateIs('connection-save-state', 'draft');
        assert.equal(await options.locator('#connection-status').isVisible(), false);
        const promptA = 'Bu örnekte yalnız imla hatalarını düzelt.';
        const promptB = 'Bu örnekte yalnız noktalama hatalarını düzelt.';
        await options.locator('#system-prompt').fill(promptA);
        await options.evaluate(() => { holdPromptSet = true; releasePromptSet = null; });
        await options.locator('#save-prompt-btn').click();
        await options.waitForFunction(() => typeof releasePromptSet === 'function');
        await options.locator('#system-prompt').fill(promptB);
        await options.evaluate(() => { holdPromptSet = false; releasePromptSet(); });
        await options.waitForFunction(() => !document.getElementById('save-prompt-btn').disabled);
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('custom_system_prompt')).custom_system_prompt), promptA);
        assert.equal(await options.locator('#system-prompt').inputValue(), promptB);
        await saveStateIs('prompt-save-state', 'draft');
        assert.equal(await options.locator('#status').isVisible(), false);
        checks.push('İzin veya kayıt yanıtı gecikirken form değişirse kaydedilen A korunuyor; bağlantı/model ve kuralların B taslağı ezilmiyor, eski başarı mesajı gösterilmiyor.');
        await worker.evaluate(() => chrome.storage.local.clear());
        await load();
        for (const scheme of ['light', 'dark']) {
            await options.emulateMedia({ colorScheme: scheme, reducedMotion: 'reduce' });
            for (const width of [320, 390, 768, 1024, 1440]) {
                await options.setViewportSize({ width, height: 1000 });
                assert.equal(await options.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `${scheme} options ${width}px overflow`);
                await capturePage(path.join(artifacts, `options-${scheme}-${width}.png`));
            }
        }
        assert.equal(await options.locator('.page-header').evaluate(node => getComputedStyle(node).animationName), 'none');
        await options.emulateMedia({ reducedMotion: 'no-preference' });
        assert.equal(await options.locator('.page-header').evaluate(node => getComputedStyle(node).animationName), 'enter');
        await options.emulateMedia({ reducedMotion: 'reduce' });
        await options.locator('#provider-select').focus();
        assert.equal(await options.evaluate(() => document.activeElement.id), 'provider-select');
        assert.equal(await options.locator('#provider-select').evaluate(node => getComputedStyle(node).outlineStyle), 'solid');
        checks.push('Açık/koyu tema, 320/390/768/1024/1440 px taşmasız; azaltılmış hareket tercihiyle animasyon yok.');
        await options.emulateMedia({ colorScheme: 'light', reducedMotion: 'reduce' });
        await options.setViewportSize({ width: 1440, height: 1000 });
        await capturePage(path.join(assets, 'options-desktop.png'));
        await options.setViewportSize({ width: 390, height: 1000 });
        await capturePage(path.join(assets, 'options-mobile.png'));
        await options.setViewportSize({ width: 1440, height: 1000 });
        await options.locator('[data-provider="openrouter"]').click();
        await options.locator('#provider-model').fill('openai/gpt-4o-mini');
        await capturePage(path.join(assets, 'options-openrouter.png'));
        await options.locator('[data-provider="ollama"]').click();
        await waitIdle();
        assert.equal(await options.locator('#provider-model').inputValue(), '');
        await options.locator('#provider-model').fill('qwen2.5:7b');
        await options.locator('#provider-model').press('Escape');
        await saveStateIs('connection-save-state', 'draft');
        await capturePage(path.join(assets, 'options-ollama.png'));
        if (await options.locator('#model-toggle').getAttribute('aria-expanded') !== 'true') await options.locator('#model-toggle').click();
        assert.equal(await options.locator('#model-options [role=option]').count(), 2);
        await capturePage(path.join(assets, 'options-model-dropdown.png'), 'model');
        await options.locator('#provider-model').press('Escape');
        await options.locator('#provider-select').click();
        await options.locator('#provider-search').fill('');
        await capturePage(path.join(assets, 'options-provider-dropdown.png'), 'provider');
        await options.keyboard.press('Escape');
        await save();
        await saveStateIs('connection-save-state', 'saved');
        await capturePage(path.join(assets, 'options-ollama-saved.png'));
        await options.locator('#base-url').fill('http://localhost:11434/v1');
        await saveStateIs('connection-save-state', 'draft');
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.providers.ollama.baseURL), 'http://127.0.0.1:11434/v1');
        await capturePage(path.join(assets, 'options-ollama-draft.png'));
        await options.setViewportSize({ width: 390, height: 1000 });
        assert.equal(await options.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Ollama mobile overflow');
        await capturePage(path.join(assets, 'options-ollama-mobile.png'));
        await options.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' });
        await options.setViewportSize({ width: 320, height: 1000 });
        assert.equal(await options.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Ollama 320px dark overflow');
        await capturePage(path.join(artifacts, 'options-ollama-dark-320.png'));
        if (!await options.locator('#local-setup-details').evaluate(node => node.open)) await options.locator('#local-setup-details > summary').click();
        if (!await options.locator('.model-install-help').evaluate(node => node.open)) await options.locator('.model-install-help > summary').click();
        for (const scheme of ['light', 'dark']) {
            await options.emulateMedia({ colorScheme: scheme, reducedMotion: 'reduce' });
            for (const width of [320, 390, 768, 1024, 1440]) {
                await options.setViewportSize({ width, height: 1000 });
                await assertCommandLayout(scheme, width);
                await captureSetup(path.join(artifacts, `options-guide-open-${scheme}-${width}.png`));
                if (width === 390 || width === 1440) await capturePage(path.join(assets, `options-guide-open-${scheme}-${width === 390 ? 'mobile' : 'desktop'}.png`));
            }
        }
        await options.emulateMedia({ colorScheme: 'light', reducedMotion: 'reduce' });
        for (const [width, name] of [[1440, 'desktop'], [390, 'mobile']]) {
            await options.setViewportSize({ width, height: 1000 });
            await captureSetup(path.join(artifacts, `ollama-setup-${name}.png`));
        }
        checks.push('Ollama yardımı 320/390/768/1024/1440 px ve açık/koyu temada taşmıyor: geniş ekranda eşit yükseklikte komut/116 px kopya sütunu, dar ekranda alt alta tam genişlik; sağ kenarlar ve özet okları düzgün.');
        checks.push('Kaydedilmiş ve adresi değiştirilmiş taslak bağlantı ile açık sağlayıcı/model menülerinin gizli bilgi içermeyen ekranları alındı.');
        await options.setViewportSize({ width: 1440, height: 1000 });
        await options.emulateMedia({ colorScheme: 'light', reducedMotion: 'reduce' });
        await worker.evaluate(() => chrome.storage.local.clear());
        await load();
        const popup = await context.newPage();
        popup.on('pageerror', error => errors.push(error.message));
        await popup.setViewportSize({ width: 380, height: 650 });
        await popup.goto(`chrome-extension://${extensionId}/popup/popup.html`);
        await popup.waitForFunction(() => !document.getElementById('enabled-toggle').disabled);
        assert.equal(await popup.locator('#enabled-toggle').isChecked(), true);
        await popup.locator('#enabled-toggle').uncheck();
        await popup.waitForFunction(() => document.getElementById('status-text').textContent.startsWith('Devre dışı'));
        assert.equal(await worker.evaluate(async () => (await chrome.storage.sync.get('ai_corrector_enabled')).ai_corrector_enabled), false);
        await popup.reload();
        await popup.waitForFunction(() => !document.getElementById('enabled-toggle').disabled);
        assert.equal(await popup.locator('#enabled-toggle').isChecked(), false);
        await popup.locator('#enabled-toggle').check();
        await popup.waitForFunction(() => document.getElementById('status-text').textContent.startsWith('Etkin'));
        assert.equal(await popup.locator('#provider-name').innerText(), 'OpenAI');
        assert.match(await popup.locator('#provider-info').innerText(), /tamamlayın/);
        checks.push('Popup aç/kapa sync alanda korunuyor; aktif sağlayıcı ve eksik bağlantı durumu gösteriliyor.');
        await popup.locator('#enabled-toggle').focus();
        await popup.keyboard.press('Tab');
        await popup.keyboard.press('Shift+Tab');
        assert.equal(await popup.locator('#enabled-toggle').evaluate(node => getComputedStyle(node.nextElementSibling).outlineStyle), 'solid');
        await popup.keyboard.press('Tab');
        assert.equal(await popup.evaluate(() => document.activeElement.id), 'open-settings');
        checks.push('Klavye odağı görünür; ana kontroller Tab ile erişilebilir.');
        const links = await popup.locator('a').evaluateAll(nodes => nodes.map(node => ({ href: node.href, target: node.target, rel: node.rel })));
        assert.equal(links.length, 3);
        links.forEach(link => { assert.equal(link.target, '_blank'); assert.match(link.rel, /noopener/); assert.equal(new URL(link.href).search, ''); });
        const pagesBefore = context.pages().length;
        await popup.waitForTimeout(150);
        assert.equal(context.pages().length, pagesBefore);
        await context.route('https://github.com/**', route => route.fulfill({ status: 200, contentType: 'text/html', body: '<title>Ürün bağlantısı</title><p>Test bağlantısı</p>' }));
        const [linkPage] = await Promise.all([context.waitForEvent('page'), popup.locator('[data-product-link="website"]').click()]);
        await linkPage.waitForLoadState();
        assert.equal(linkPage.url(), 'https://github.com/mytsx/duzelt-ai');
        await linkPage.close();
        await popup.evaluate(() => {
            const nativeOpen = chrome.runtime.openOptionsPage.bind(chrome.runtime);
            globalThis.optionsOpened = null;
            chrome.runtime.openOptionsPage = callback => nativeOpen(() => {
                optionsOpened = !chrome.runtime.lastError;
                callback();
            });
        });
        await popup.locator('#open-settings').click();
        await popup.waitForFunction(() => optionsOpened === true);
        assert.ok(context.pages().some(page => page.url().endsWith('/options/options.html')));
        checks.push('Ürün bağlantısı ve Ayarları yönet düğmesi gerçek tıklamayla doğru sayfayı açıyor; kendiliğinden sekme yok.');
        await popup.locator('#open-settings').evaluate(node => node.blur());
        const bounds = await popup.locator('body').boundingBox();
        assert.ok(bounds.height < 600);
        for (const scheme of ['light', 'dark']) {
            await popup.emulateMedia({ colorScheme: scheme, reducedMotion: 'reduce' });
            await popup.screenshot({ path: path.join(assets, `popup-${scheme}.png`), clip: bounds });
        }
        assert.deepEqual(errors, []);
        checks.push('Gerçek eklenti sayfalarında JavaScript hatası yok; ekranlar sır içermeden alındı.');
        const result = { checkedOn: '2026-10-03', extensionVersion: await worker.evaluate(() => chrome.runtime.getManifest().version), browser: await context.browser().version(), checkCount: checks.length, checks, realProviderCall: false, permissionDialogFixture: true, clipboardFixture: true, disposableProfile: true, captureOffscreenSkipLinkSuppressed: offscreenSkipLinkCaptures > 0, captureOffscreenSkipLinkReason: 'Chromium beyond-viewport clipping can include the unfocused fixed skip-link with boundingClientRect.bottom < 0; only that offscreen element is hidden during reference capture and its original style is restored in finally.', visualReviewPending: true };
        await fs.writeFile(path.join(artifacts, 'ui-results.json'), JSON.stringify(result, null, 2));
        console.log(JSON.stringify(result, null, 2));
    } finally { if (context) await context.close(); await fs.rm(profile, { recursive: true, force: true }); }
})().catch(error => { console.error(error); process.exitCode = 1; });
