/* Unpacked extension in a disposable profile; provider traffic and optional grant dialogs use deterministic fixtures. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
(async () => {
    const root = path.resolve(__dirname, '..');
    const profile = await fs.mkdtemp(path.join(os.tmpdir(), 'duzelt-ui-'));
    const artifacts = path.join(root, 'output/playwright');
    const assets = path.join(root, 'design/claude-assets');
    await fs.mkdir(artifacts, { recursive: true });
    await fs.mkdir(assets, { recursive: true });
    const checks = [];
    let context;
    try {
        context = await chromium.launchPersistentContext(profile, { channel: 'chromium', headless: true, args: [`--disable-extensions-except=${root}`, `--load-extension=${root}`], viewport: { width: 1024, height: 900 } });
        const worker = context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
        const extensionId = new URL(worker.url()).host;
        await worker.evaluate(() => {
            globalThis.testCalls = [];
            globalThis.fixtureFailure = false;
            chrome.permissions.contains = (value, callback) => callback(true);
            globalThis.fetch = async (url, init) => {
                const body = init.body && String(init.body).startsWith('{') ? JSON.parse(init.body) : null;
                testCalls.push({ url: String(url), method: init.method, model: body?.model || body?.model_id || body?.config?.modules?.prompt_templating?.model?.name, userText: body?.messages?.find(item => item.role === 'user')?.content });
                if (fixtureFailure) return new Response(JSON.stringify({ error: { message: 'never expose fixture detail', code: 'invalid_api_key' } }), { status: 401 });
                if (String(url).includes('/identity/token') || String(url).endsWith('/oauth/token')) return new Response(JSON.stringify({ access_token: 'fixture-access-token', token_type: 'Bearer', expires_in: 3600 }), { status: 200 });
                if (!body) return new Response(JSON.stringify({ data: [{ id: 'test-model', name: 'Test Model' }] }), { status: 200 });
                const output = JSON.stringify({ corrected_text: 'Bu bir test metnidir.' });
                return new Response(JSON.stringify(String(url).endsWith('/v2/completion') ? { final_result: { choices: [{ finish_reason: 'stop', message: { content: output } }] } } : String(url).includes(':generateContent') ? { candidates: [{ finishReason: 'STOP', content: { parts: [{ text: output }] } }] } : { choices: [{ finish_reason: 'stop', message: { content: output } }] }), { status: 200 });
            };
        });
        const errors = [];
        const options = await context.newPage();
        options.on('pageerror', error => errors.push(error.message));
        await options.addInitScript(() => {
            globalThis.permissionRequests = [];
            globalThis.grantPermission = true;
            chrome.permissions.request = (request, callback) => { permissionRequests.push(request); callback(grantPermission); };
        });
        const load = async () => {
            await options.goto(`chrome-extension://${extensionId}/options/options.html`);
            await options.waitForFunction(() => document.getElementById('system-prompt').value.length > 0 && !document.getElementById('test-btn').disabled);
        };
        const statusHas = async text => { try { await options.waitForFunction(value => document.getElementById('connection-status').textContent.includes(value), text); } catch (error) { console.error({expectedStatus:text,actualStatus:await options.locator('#connection-status').innerText()}); throw error; } };
        const save = async () => { await options.locator('#save-api-btn').click(); await statusHas('etkinleştirildi'); };
        await load();
        assert.equal(await options.locator('#openai-key').getAttribute('type'), 'password');
        assert.ok(await options.locator('#provider-select option').count() > 200);
        await options.locator('#test-btn').click();
        await statusHas('API anahtarı');
        assert.equal(await worker.evaluate(() => testCalls.length), 0);
        checks.push('Eksik anahtar, ağ isteği yapılmadan gösteriliyor; katalog yerel olarak yükleniyor.');
        await options.locator('#openai-key').fill('Türkçe geçersiz anahtar');
        await options.locator('#save-api-btn').click();
        await statusHas('geçersiz');
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config), undefined);
        checks.push('Geçersiz anahtar depoya yazılmıyor.');
        await worker.evaluate(() => chrome.storage.local.set({ openai_api_key: 'fixture-openai-legacy' }));
        await load();
        assert.equal(await options.locator('#openai-key').inputValue(), 'fixture-openai-legacy');
        assert.equal(await options.locator('#provider-model').inputValue(), 'gpt-4o');
        await save();
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.providers.openai.apiKey), 'fixture-openai-legacy');
        checks.push('Eski OpenAI anahtarı ve gpt-4o, merkezi yapılandırmaya kayıpsız taşınıyor.');
        await options.locator('[data-provider="openrouter"]').click();
        await options.locator('#provider-model').fill('openai/gpt-4o-mini');
        await options.locator('#openai-key').fill('fixture-openrouter');
        await options.evaluate(() => { grantPermission = false; });
        await options.locator('#save-api-btn').click();
        await statusHas('izni verilmedi');
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.activeProviderId), 'openai');
        assert.deepEqual(await options.evaluate(() => permissionRequests.at(-1).origins), ['https://openrouter.ai/*']);
        await options.evaluate(() => { grantPermission = true; });
        await save();
        const config = await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config);
        assert.equal(config.activeProviderId, 'openrouter');
        assert.equal(config.providers.openai.apiKey, 'fixture-openai-legacy');
        checks.push('OpenRouter için belirli alan izni; izin reddi aktif seçimi koruyor, izin sonrası ayrı profiller kaydediliyor.');
        await options.locator('#provider-model').fill('unsaved-model');
        await options.locator('#openai-key').fill('unsaved-secret');
        await options.locator('#test-btn').click();
        await statusHas('Bağlantı başarılı');
        const call = await worker.evaluate(() => testCalls.at(-1));
        assert.equal(call.model, 'openai/gpt-4o-mini');
        assert.equal(call.url, 'https://openrouter.ai/api/v1/chat/completions');
        assert.equal(call.userText, 'Bu bir test metnidir.');
        checks.push('Test yalnız kaydedilmiş sağlayıcı/modeli ve kısa örnek metni kullanıyor.');
        await options.locator('#refresh-models').click();
        await statusHas('sağlayıcıdan alındı');
        assert.equal(await worker.evaluate(() => testCalls.at(-1).url), 'https://openrouter.ai/api/v1/models');
        await options.locator('#provider-model').fill('test');
        assert.equal(await options.locator('#model-options option').first().getAttribute('value'), 'test-model');
        checks.push('Model yenileme kullanıcı tıklamasıyla kayıtlı bağlantıdan alınıyor.');
        await worker.evaluate(() => { fixtureFailure = true; });
        await options.locator('#test-btn').click();
        await statusHas('kabul etmedi');
        assert.equal((await options.locator('#connection-status').innerText()).includes('never expose'), false);
        await worker.evaluate(() => { fixtureFailure = false; });
        checks.push('Bağlantı hatası güvenli metinle gösteriliyor; sağlayıcının ham mesajı açığa çıkmıyor.');
        await options.locator('#provider-select').selectOption('github-copilot');
        assert.equal(await options.locator('#save-api-btn').isDisabled(), true);
        assert.match(await options.locator('#provider-note').innerText(), /CLI|runtime|kimlik/);
        checks.push('Özel ürün girişi ve çalışma ortamı isteyen kayıtlar açıklamalarıyla görünür; yanlış API anahtarı yoluyla etkinleştirilemiyor.');
        await options.locator('#provider-select').selectOption('azure');
        assert.equal(await options.locator('#profile-resourceName').count(), 1);
        await options.locator('#provider-select').selectOption('ollama');
        assert.equal(await options.locator('#openai-key').isDisabled(), true);
        await options.locator('#provider-model').fill('qwen2.5:7b');
        await save();
        assert.deepEqual(await options.evaluate(() => permissionRequests.at(-1).origins), ['http://127.0.0.1:11434/*']);
        checks.push('Kurumsal alanlar katalogdan oluşuyor; Ollama anahtarsız yerel profil olarak kaydediliyor.');
        await options.locator('#provider-select').selectOption('watsonx');
        await options.locator('#provider-model').fill('fixture-native-chat');
        await options.locator('#openai-key').fill('fixture-ibm-key');
        await options.locator('#profile-projectId').fill('fixture-project');
        await save();
        assert.deepEqual(await options.evaluate(() => permissionRequests.at(-1).origins), ['https://us-south.ml.cloud.ibm.com/*', 'https://iam.cloud.ibm.com/*']);
        await options.locator('#test-btn').click();
        await statusHas('Bağlantı başarılı');
        assert.ok((await worker.evaluate(() => testCalls.at(-1).url)).includes('/ml/v1/text/chat?version='));
        checks.push('IBM IAM ve inference adresleri için ayrı izinler isteniyor; API anahtarıyla belirteç alıp yerel fixture düzeltmesi tamamlanıyor.');
        await options.locator('#provider-select').selectOption('sap-ai-core');
        assert.equal(await options.locator('#provider-key-group').isVisible(), false);
        assert.equal(await options.locator('#profile-clientSecret').getAttribute('type'), 'password');
        await options.locator('#profile-clientId').fill('fixture-client');
        await options.locator('#profile-clientSecret').fill('fixture-sap-secret');
        await options.locator('#profile-tokenURL').fill('https://auth.example/oauth/token');
        await options.locator('#profile-deploymentId').fill('fixture-deployment');
        await options.locator('#profile-resourceGroup').fill('fixture-group');
        await options.locator('#provider-model').fill('gpt-4o');
        await options.locator('#base-url').fill('https://sap.example');
        assert.equal(await options.locator('#profile-sapMode').inputValue(), 'orchestration');
        await save();
        assert.deepEqual(await options.evaluate(() => permissionRequests.at(-1).origins), ['https://sap.example/*', 'https://auth.example/*']);
        await options.locator('#test-btn').click();
        await statusHas('Bağlantı başarılı');
        assert.ok((await worker.evaluate(() => testCalls.at(-1).url)).endsWith('/v2/completion'));
        assert.equal(await worker.evaluate(async () => JSON.stringify(await chrome.storage.local.get(null)).includes('fixture-access-token')), false);
        assert.equal(await worker.evaluate(async () => Object.hasOwn(await chrome.storage.sync.get(null), 'ai_provider_config')), false);
        checks.push('SAP giriş alanları ve orkestrasyon seçimi merkezi formda çalışıyor; iki adres izinli, alınan belirteç ve profiller Sync depoya yazılmıyor.');
        await options.locator('#provider-select').selectOption('custom');
        await options.locator('#provider-model').fill('my-model');
        await options.locator('#advanced-settings').evaluate(node => { node.open = true; });
        await options.locator('#base-url').fill('http://remote.example/v1');
        await options.locator('#save-api-btn').click();
        await statusHas('HTTPS');
        await options.locator('#base-url').fill('https://proxy.example/v1?key=bad');
        await options.locator('#save-api-btn').click();
        await statusHas('sorgu');
        const active = await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.activeProviderId);
        assert.equal(active, 'sap-ai-core');
        checks.push('Güvensiz uzak HTTP ve anahtar içerebilecek sorgulu adresler kaydedilmiyor.');
        await options.locator('#system-prompt').fill('Yalnız imla ve noktalama hatalarını düzelt.');
        await options.locator('#save-prompt-btn').click();
        await options.waitForFunction(() => document.getElementById('status').textContent.includes('kaydedildi'));
        await load();
        assert.equal(await options.locator('#system-prompt').inputValue(), 'Yalnız imla ve noktalama hatalarını düzelt.');
        await options.locator('#system-prompt').fill('');
        await options.locator('#save-prompt-btn').click();
        await options.waitForFunction(() => document.getElementById('status').textContent.includes('Varsayılan'));
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('custom_system_prompt')).custom_system_prompt), undefined);
        checks.push('Ortak özel kurallar local alanda korunuyor; boş kaydetmek varsayılana dönüyor.');
        await options.locator('[data-provider="openai"]').click();
        await options.locator('#openai-key').fill('');
        await save();
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('openai_api_key')).openai_api_key), undefined);
        assert.equal(await worker.evaluate(async () => (await chrome.storage.local.get('ai_provider_config')).ai_provider_config.providers.openai.apiKey), '');
        checks.push('Anahtar silme eski kaydı da temizliyor; başka sağlayıcıya gizli geçiş yapılmıyor.');
        await worker.evaluate(() => chrome.storage.local.clear());
        await load();
        for (const scheme of ['light', 'dark']) {
            await options.emulateMedia({ colorScheme: scheme, reducedMotion: 'reduce' });
            for (const width of [320, 390, 768, 1024, 1440]) {
                await options.setViewportSize({ width, height: 1000 });
                assert.equal(await options.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `${scheme} options ${width}px overflow`);
                await options.screenshot({ path: path.join(artifacts, `options-${scheme}-${width}.png`), fullPage: true });
            }
        }
        assert.equal(await options.locator('.page-header').evaluate(node => getComputedStyle(node).animationName), 'none');
        await options.emulateMedia({ reducedMotion: 'no-preference' });
        assert.equal(await options.locator('.page-header').evaluate(node => getComputedStyle(node).animationName), 'enter');
        await options.emulateMedia({ reducedMotion: 'reduce' });
        await options.locator('#provider-search').focus();
        await options.keyboard.press('Tab');
        assert.equal(await options.evaluate(() => document.activeElement.id), 'provider-select');
        assert.equal(await options.locator('#provider-select').evaluate(node => getComputedStyle(node).outlineStyle), 'solid');
        checks.push('Açık/koyu tema, 320/390/768/1024/1440 px taşmasız; azaltılmış hareket tercihiyle animasyon yok.');
        await options.emulateMedia({ colorScheme: 'light', reducedMotion: 'reduce' });
        await options.setViewportSize({ width: 1440, height: 1000 });
        await options.screenshot({ path: path.join(assets, 'options-desktop.png'), fullPage: true });
        await options.setViewportSize({ width: 390, height: 1000 });
        await options.screenshot({ path: path.join(assets, 'options-mobile.png'), fullPage: true });
        await options.setViewportSize({ width: 1440, height: 1000 });
        await options.locator('[data-provider="openrouter"]').click();
        await options.locator('#provider-model').fill('openai/gpt-4o-mini');
        await options.screenshot({ path: path.join(assets, 'options-openrouter.png'), fullPage: true });
        await options.locator('[data-provider="openai"]').click();
        const popup = await context.newPage();
        popup.on('pageerror', error => errors.push(error.message));
        await popup.setViewportSize({ width: 380, height: 650 });
        await popup.goto(`chrome-extension://${extensionId}/popup/popup.html`);
        await popup.waitForFunction(() => !document.getElementById('enabled-toggle').disabled);
        assert.equal(await popup.locator('#enabled-toggle').isChecked(), true);
        await popup.locator('#enabled-toggle').uncheck();
        await popup.waitForFunction(() => document.getElementById('status-text').textContent.startsWith('Devre dışı'));
        assert.equal(await worker.evaluate(async () => (await chrome.storage.sync.get('ai_corrector_enabled')).ai_corrector_enabled), false);
        await popup.reload();
        await popup.waitForFunction(() => !document.getElementById('enabled-toggle').disabled);
        assert.equal(await popup.locator('#enabled-toggle').isChecked(), false);
        await popup.locator('#enabled-toggle').check();
        await popup.waitForFunction(() => document.getElementById('status-text').textContent.startsWith('Etkin'));
        assert.equal(await popup.locator('#provider-name').innerText(), 'OpenAI');
        assert.match(await popup.locator('#provider-info').innerText(), /tamamlayın/);
        checks.push('Popup aç/kapa sync alanda korunuyor; aktif sağlayıcı ve eksik bağlantı durumu gösteriliyor.');
        await popup.locator('#enabled-toggle').focus();
        await popup.keyboard.press('Tab');
        await popup.keyboard.press('Shift+Tab');
        assert.equal(await popup.locator('#enabled-toggle').evaluate(node => getComputedStyle(node.nextElementSibling).outlineStyle), 'solid');
        await popup.keyboard.press('Tab');
        assert.equal(await popup.evaluate(() => document.activeElement.id), 'open-settings');
        checks.push('Klavye odağı görünür; ana kontroller Tab ile erişilebilir.');
        const links = await popup.locator('a').evaluateAll(nodes => nodes.map(node => ({ href: node.href, target: node.target, rel: node.rel })));
        assert.equal(links.length, 3);
        links.forEach(link => { assert.equal(link.target, '_blank'); assert.match(link.rel, /noopener/); assert.equal(new URL(link.href).search, ''); });
        const pagesBefore = context.pages().length;
        await popup.waitForTimeout(150);
        assert.equal(context.pages().length, pagesBefore);
        await context.route('https://github.com/**', route => route.fulfill({ status: 200, contentType: 'text/html', body: '<title>Ürün bağlantısı</title><p>Test bağlantısı</p>' }));
        const [linkPage] = await Promise.all([context.waitForEvent('page'), popup.locator('[data-product-link="website"]').click()]);
        await linkPage.waitForLoadState();
        assert.equal(linkPage.url(), 'https://github.com/mytsx/duzelt-ai');
        await linkPage.close();
        await popup.evaluate(() => {
            const nativeOpen = chrome.runtime.openOptionsPage.bind(chrome.runtime);
            globalThis.optionsOpened = null;
            chrome.runtime.openOptionsPage = callback => nativeOpen(() => {
                optionsOpened = !chrome.runtime.lastError;
                callback();
            });
        });
        await popup.locator('#open-settings').click();
        await popup.waitForFunction(() => optionsOpened === true);
        assert.ok(context.pages().some(page => page.url().endsWith('/options/options.html')));
        checks.push('Ürün bağlantısı ve Ayarları yönet düğmesi gerçek tıklamayla doğru sayfayı açıyor; kendiliğinden sekme yok.');
        await popup.locator('#open-settings').evaluate(node => node.blur());
        const bounds = await popup.locator('body').boundingBox();
        assert.ok(bounds.height < 600);
        for (const scheme of ['light', 'dark']) {
            await popup.emulateMedia({ colorScheme: scheme, reducedMotion: 'reduce' });
            await popup.screenshot({ path: path.join(assets, `popup-${scheme}.png`), clip: bounds });
        }
        assert.deepEqual(errors, []);
        checks.push('Gerçek eklenti sayfalarında JavaScript hatası yok; ekranlar sır içermeden alındı.');
        const result = { checkedOn: '2026-10-03', extensionVersion: '3.4.0', browser: await context.browser().version(), checkCount: checks.length, checks, realProviderCall: false, permissionDialogFixture: true, visualReviewPending: true };
        await fs.writeFile(path.join(artifacts, 'ui-results.json'), JSON.stringify(result, null, 2));
        console.log(JSON.stringify(result, null, 2));
    } finally { if (context) await context.close(); await fs.rm(profile, { recursive: true, force: true }); }
})().catch(error => { console.error(error); process.exitCode = 1; });
